# Generated by Django 3.0.6 on 2020-05-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='음식점 이름')),
                ('content', models.TextField(verbose_name='음식점 설명')),
                ('positive_count', models.IntegerField(default=0, verbose_name='좋아요 수')),
                ('negative_count', models.IntegerField(default=0, verbose_name='싫어요 수')),
            ],
        ),
    ]
